# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../../storage-base

patches:
  - options:
      allowNameChange: true
    path: rename.patch.yaml
    target:
      kind: Deployment
  - path: deployment.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
